"""Cordis: a composition kernel for Python applications.

An application built on Cordis is a tree of mounted plugins. Every plugin
receives a `Context`, contributes capabilities through it, and every
contribution is reversible: unloading a plugin unwinds exactly what it
registered, including everything it mounted in turn.

The public surface is assembled here as each capability lands. The contract
each name implements lives in ``spec/capabilities/`` -- one YAML record per
capability, carrying its normative rules and the property cards that test them.

One module is deliberately absent: :mod:`cordis.exporters` is imported by name,
never from here, so ``import cordis`` reaches nothing that touches the standard
library's ``logging`` on an application's behalf. The module object itself
arrives anyway -- ``asyncio`` imports it -- but no logger is made, no handler is
installed and no level is set until an application asks for output.
"""

from __future__ import annotations

from cordis.config import (
    CONFIG_SCHEMA_ATTR,
    ConfigIssue,
    ConfigResult,
    ConfigSchema,
    config_schema,
    from_dataclass,
    resolve_config,
    schema_of,
)
from cordis.context import Context, ServiceResolver
from cordis.diagnostics import (
    Blockage,
    FiberSnapshot,
    PendingReport,
    inspect,
    pending,
    render_tree,
    walk,
)
from cordis.effect import EffectHandle, EffectScope
from cordis.errors import (
    MOUNT_NOTE_PREFIX,
    AsyncValidationError,
    ConfigValidationError,
    CordisError,
    DependencyCycleError,
    EventModeError,
    ExpressionError,
    InactiveScopeError,
    InvalidEffectError,
    InvalidPluginError,
    IssueLike,
    NextCalledTwiceError,
    PatchTargetError,
    RegistryConflictError,
    ServiceConflictError,
    ServiceNotFoundError,
    attribute_mount_site,
    mount_attribution,
    mount_sites,
)
from cordis.events import (
    Bail,
    BoundBus,
    Emit,
    ErrorReport,
    Event,
    EventBus,
    Next,
    Parallel,
    Serial,
    Waterfall,
)
from cordis.expr import (
    BUDGET,
    ENVELOPE,
    FUNCTIONS,
    MAX_DEPTH,
    TAG,
    CompiledExpr,
    Expr,
    FunctionSource,
    Opaque,
    Problem,
    compile_expr,
    envelope_of,
    evaluate,
    expression_paths,
    is_envelope,
    opaque,
    parse_expressions,
    substitute,
    unparse_expressions,
    yaml_loader,
)
from cordis.fiber import (
    SETTLED,
    TRANSITIONS,
    Fiber,
    FiberRuntime,
    FiberState,
    IllegalTransitionError,
    ProblemListener,
    StatusChange,
    StatusListener,
)
from cordis.filter import (
    FILTER_KEY,
    Filter,
    filter_of,
    with_filter,
)
from cordis.hmr import (
    RELOAD_FLAG,
    HmrService,
    ReloadFailure,
    ReloadReport,
    affected,
    declines,
    escalated,
    import_graph,
    imports_of,
    project_module,
    reload_order,
)
from cordis.inject import (
    Token,
    dependencies_of,
    inject,
    provisions_of,
)
from cordis.intercept import (
    INTERCEPT_KEY,
    Interception,
    InterceptResolver,
    effective_config,
    intercept,
    intercept_all,
    intercept_key,
    intercepted_names,
    interceptions,
    merge_interceptions,
)
from cordis.layering import (
    BASE,
    Fields,
    Layer,
    Patch,
    Resolution,
    read_layer,
    resolve,
    wrote,
)
from cordis.loader import (
    GROUP,
    Entry,
    EntryFailure,
    FileSource,
    ImportTargets,
    JsonSource,
    LoaderService,
    MappingSource,
    ReconcileReport,
    TargetSource,
    TomlSource,
    YamlSource,
    as_mapping,
    read_entries,
)
from cordis.logging import (
    DEFAULT_BUFFER,
    DETACHED,
    Exporter,
    ExportFailure,
    Level,
    Logger,
    LoggerService,
    Record,
    logger,
)
from cordis.plugin import (
    FIBER_KEY,
    ConfigPreparer,
    PluginForm,
    PluginHandle,
    PluginHost,
    PluginTarget,
    config_of,
    fiber_of,
    normalise,
    scope_of,
)
from cordis.realm import (
    Isolation,
    isolate,
    isolated_names,
    isolated_realm,
)
from cordis.registry import (
    DEFAULT_REALM,
    BindingChange,
    BindingInfo,
    ChangeKind,
    Realm,
    Service,
    ServiceRegistry,
    enter_realm,
    realm_for,
    realm_key,
    realm_of,
    service_name,
    token_label,
)
from cordis.scope import (
    SUBJECT_KEY,
    Scope,
    ScopedRegistry,
    admits,
    create_scope,
    scope_target,
    subject_of,
)
from cordis.seam import (
    UNSET,
    Candidate,
    Definition,
    Registry,
    RegistryChange,
    RegistryFailure,
    resolve_spec,
)
from cordis.timer import (
    Clock,
    Report,
    Schedule,
    SystemClock,
    TimerFailure,
    clock_of,
    debounce,
    interval,
    spawn,
    throttle,
    timeout,
)

__all__ = [
    "BASE",
    "BUDGET",
    "CONFIG_SCHEMA_ATTR",
    "DEFAULT_BUFFER",
    "DEFAULT_REALM",
    "DETACHED",
    "ENVELOPE",
    "FIBER_KEY",
    "FILTER_KEY",
    "FUNCTIONS",
    "GROUP",
    "INTERCEPT_KEY",
    "MAX_DEPTH",
    "MOUNT_NOTE_PREFIX",
    "RELOAD_FLAG",
    "SETTLED",
    "SUBJECT_KEY",
    "TAG",
    "TRANSITIONS",
    "UNSET",
    "AsyncValidationError",
    "Bail",
    "BindingChange",
    "BindingInfo",
    "Blockage",
    "BoundBus",
    "Candidate",
    "ChangeKind",
    "Clock",
    "CompiledExpr",
    "ConfigIssue",
    "ConfigPreparer",
    "ConfigResult",
    "ConfigSchema",
    "ConfigValidationError",
    "Context",
    "CordisError",
    "Definition",
    "DependencyCycleError",
    "EffectHandle",
    "EffectScope",
    "Emit",
    "Entry",
    "EntryFailure",
    "ErrorReport",
    "Event",
    "EventBus",
    "EventModeError",
    "ExportFailure",
    "Exporter",
    "Expr",
    "ExpressionError",
    "Fiber",
    "FiberRuntime",
    "FiberSnapshot",
    "FiberState",
    "Fields",
    "FileSource",
    "Filter",
    "FunctionSource",
    "HmrService",
    "IllegalTransitionError",
    "ImportTargets",
    "InactiveScopeError",
    "InterceptResolver",
    "Interception",
    "InvalidEffectError",
    "InvalidPluginError",
    "Isolation",
    "IssueLike",
    "JsonSource",
    "Layer",
    "Level",
    "LoaderService",
    "Logger",
    "LoggerService",
    "MappingSource",
    "Next",
    "NextCalledTwiceError",
    "Opaque",
    "Parallel",
    "Patch",
    "PatchTargetError",
    "PendingReport",
    "PluginForm",
    "PluginHandle",
    "PluginHost",
    "PluginTarget",
    "Problem",
    "ProblemListener",
    "Realm",
    "ReconcileReport",
    "Record",
    "Registry",
    "RegistryChange",
    "RegistryConflictError",
    "RegistryFailure",
    "ReloadFailure",
    "ReloadReport",
    "Report",
    "Resolution",
    "Schedule",
    "Scope",
    "ScopedRegistry",
    "Serial",
    "Service",
    "ServiceConflictError",
    "ServiceNotFoundError",
    "ServiceRegistry",
    "ServiceResolver",
    "StatusChange",
    "StatusListener",
    "SystemClock",
    "TargetSource",
    "TimerFailure",
    "Token",
    "TomlSource",
    "Waterfall",
    "YamlSource",
    "admits",
    "affected",
    "as_mapping",
    "attribute_mount_site",
    "clock_of",
    "compile_expr",
    "config_of",
    "config_schema",
    "create_scope",
    "debounce",
    "declines",
    "dependencies_of",
    "effective_config",
    "enter_realm",
    "envelope_of",
    "escalated",
    "evaluate",
    "expression_paths",
    "fiber_of",
    "filter_of",
    "from_dataclass",
    "import_graph",
    "imports_of",
    "inject",
    "inspect",
    "intercept",
    "intercept_all",
    "intercept_key",
    "intercepted_names",
    "interceptions",
    "interval",
    "is_envelope",
    "isolate",
    "isolated_names",
    "isolated_realm",
    "logger",
    "merge_interceptions",
    "mount_attribution",
    "mount_sites",
    "normalise",
    "opaque",
    "parse_expressions",
    "pending",
    "project_module",
    "provisions_of",
    "read_entries",
    "read_layer",
    "realm_for",
    "realm_key",
    "realm_of",
    "reload_order",
    "render_tree",
    "resolve",
    "resolve_config",
    "resolve_spec",
    "schema_of",
    "scope_of",
    "scope_target",
    "service_name",
    "spawn",
    "subject_of",
    "substitute",
    "throttle",
    "timeout",
    "token_label",
    "unparse_expressions",
    "walk",
    "with_filter",
    "wrote",
    "yaml_loader",
]

#: The one place the version is written: the build reads it from here rather
#: than the other way round, so `cordis.__version__` costs no import and cannot
#: disagree with what was published.
__version__ = "0.1.0"
